---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: grapeupci/java
    tag: latest

inputs:
- name: sourcecode

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x ./sourcecode/ci/tasks/perm-patch.sh
    ./sourcecode/ci/tasks/perm-patch.sh ./sourcecode/ci/tasks/build.sh
