---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest


resources:
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-webhook-address))

- name: sourcecode
  type: git
  source:
    uri: git@github.com:project-io-group/vmms-backend.git
    branch: ((branch))
    private_key: ((git-private-key))

- name: pws-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: vmms
    password: AGH_ust_1919
    skip_cert_check: true
    space: development
    username: project.io.group.git.bot@gmail.com


jobs:
- name: build-and-upload
  serial: true
  plan:
  - get: sourcecode
    trigger: true
  - task: build
    file: sourcecode/ci/tasks/build.yml
  - put: pws-cf
    params:
      manifest: sourcecode/ci/manifest.yml
      path: build/vmms-backend-0.0.1-SNAPSHOT.jar
  on_failure:
    put: slack-alert
    params:
      channel: '#builds'
      text: |
        The build failed. Check it out at:
        http://35.180.56.35:8080//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        http://35.180.56.35:8080//builds/$BUILD_ID
