---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest


resources:
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-webhook-address))

- name: sourcecode
  type: git
  source:
    uri: git@github.com:project-io-group/vmms-backend.git
    branch: master
    private_key: ((git-private-key))


jobs:
- name: build
  on_failure:
    put: slack-alert
    params:
      channel: '#builds'
      text: |
        The build failed. Check it out at:
        http://my.concourse.url/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        http://my.concourse.url/builds/$BUILD_ID
  plan:
  - get: sourcecode
    trigger: true
  - task: build
    file: sourcecode/ci/tasks/build.yml
